### ISSUE TITLE
Ignoring iframes with a certain class

### ISSUE THREAD

**Issue by jjuspe** [rosszurowski/fitvids#9]
This maybe a stupid question, but I can't figure out how to ignore iframes with a certain class. 
I noticed the `ignore` option but I don't what to pass to it, since I don't know what `['object']` should be. Or is it even possible?

**Comment by rosszurowski** [comment]
There is an "ignore" behaviour, but it's a rather odd one: selectors passed via `ignore` are filtered from the default list of selectors fitvids will search for (`iframe[src*="youtube.com"]`, `iframe[src*="vimeo.com"]`, etc.) rather than the final matched elements.

What you described, ignoring videos by any selector, makes a lot more sense. I've opened PR #10 to add this behaviour.

**Comment by rosszurowski** [comment]
Published in v2.1.0 with eb348e1
